  
version: '3.1'
services:
  nexus:
    image: waltonmax/nexus:latest
    container_name: nexus
    network_mode: host
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - /data/nexus/data:/data/nexus
    logging:
      driver: "json-file"
      options:
        max-size: "200M"